export const LABELS = {
    home: "Home",
    services: "Services",
    search: "Search...",
    darkMode: "Dark Mode",
    footerLabel: "Powered by",
    logoAltText: "Spectrum Logo",
    continueButtonLabel: "Continue",
    previousButtonLabel: "Previous",
    continue: "continue",
    previous: "previous",
    backtoHome: "backToHome",
    userFormHeading: "Please confirm or add to the below GP Contact Details.",
    gpNameLabel: "GP Name",
    emailLabel: "Email",
    contactLabel: "Contact Number",
    validationGPMessage: "Please enter GP Name",
    validationEmailMessage: "Please enter Email",
    validationContactMessage: "Please enter a valid Contact Number",
    validationEmailInvalidMessage: "Please enter a valid Email",
};