export const LABELS = {
    home: "Home",
    services: "Services",
    search: "Search...",
    darkMode: "Dark Mode",
    footerLabel: "Powered by",
    logoAltText: "Spectrum Logo",
    continueButtonLabel: "Continue",
    previousButtonLabel: "Previous",
    continue: "continue",
    previous: "previous",
    backtoHome: "backToHome",
    userFormHeading: "Please confirm or add to the below GP Contact Details.",
    gpNameLabel: "GP Name",
    emailLabel: "Email",
    contactLabel: "Contact Number",
    validationGPMessage: "Please enter GP Name",
    validationEmailMessage: "Please enter Email",
    validationContactMessage: "Please enter a valid Contact Number",
    validationEmailInvalidMessage: "Please enter a valid Email",
    confirmationTitle: "Booking Confirmed!",
    confirmationMessage: "You should soon receive an email confirming your booking, followed by a reminder email the day before your appointment to your registered email address.",
    descriptionLabel: " To attend or cancel your session, go to the booking area by clicking the calendar icon in the top navigation.",
    appointmentFormatLabel: "Select your preferred appointment format",
    video: "Video",
    audio: "Audio",
    importantNoteTitle: "Important Note",
    alertMessage: "For both audio appointments and video appointments, you will need to return to the portal to join your session at the scheduled time.",
    alertMessage2: "Clinicians do not call users directly. Ensure you log in a few minutes before your appointment to avoid missing your session.",
    returnToHome: "Return to Home"
};